### PR TITLE
Updated dependencies versions (grpc, protobuf, test)

### PR DESCRIPTION
**Pull request by guyluz11**
Updated dependencies (grpc, protobuf, test).

Tests are passing exept for the regular two.

### CODE REVIEW

**Comment by cachapa** [comment]
Is there any strong reason for upgrading the dependencies?

The caret syntax already picks the latest minor version when you update your dependencies anyway: https://dart.dev/tools/pub/dependencies#caret-syntax

**Comment by guyluz11** [comment]
No reason except to keep being updated.

**Comment by cachapa** [comment]
Ok, then I'll close this PR without merging.
I typically update the dependencies opportunistically as part of other work, otherwise the git history gets spammed with trivial entries.

**Comment by guyluz11** [comment]
Sure

**Pull request closed without merging**
