### PR TITLE
Silence noisy log

### PR DESCRIPTION
**Pull request by simonbengtsson**

### CODE REVIEW

**Comment by cachapa** [comment]
I'm a bit confused, what's this supposed to do, and what's the reasoning for it?

Also, your PR just adds another print statement, the reverse of silencing a noisy log?

**Comment by simonbengtsson** [comment]
I think the PR remove the print in [firestore_gateway.dart#L211](https://github.com/cachapa/firedart/blob/master/lib/firestore/firestore_gateway.dart#L211) (shown below as well)? I'm retrying a connection every a few seconds and this was logged a lot in the console.

```dart
print('Handling error $e using FirestoreGateway._handleError');
```

**Comment by cachapa** [comment]
Oh, sorry I read it wrong.

In any case this project is currently on life support since I don't have the time to moderate it properly.
When I do have that time, I'll have to do a bigger rewrite which makes this PR redundant anyway, so I'll close this for now.

Thank you for taking the time in any case.

**Comment by simonbengtsson** [comment]
Thanks for considering it anyhow! I'm using firedart for the Airdash app and it has been working amazingly well. If there is anything I can do to help let me know 👌

**Pull request closed without merging**
