### PR TITLE
Implement stream caching for collection and document listeners

### PR DESCRIPTION
**Pull request by cenomla**
Change log:
 - Implement stream caching with request lifetime tied to stream listeners
 - Fix stream data crossing bug

This fixes issues #53 and #52 and maybe #55

### CODE REVIEW

**Comment by cachapa** [comment]
Thanks for the contribution.

You seem to have changed the formatting for lines which weren't changed, which makes code reviewing a bit more difficult.
The quality gate checks for formatting anyway, so the merge won't go through until it's satisfied.

Just run `dart format .` in the firedart directory. It might take a while (30s on my machine) due to the generated protobuff files.

**Comment by cachapa** [comment]
You might also want to rebase on top of the latest commit, which fixes some issues with the quality gate

**Comment by cenomla** [comment]
Rebased and re-formatted. Looks like checks are passing now

**Review by cachapa — APPROVED** [review]
LGTM

**Comment by cachapa** [comment]
Thanks!

**Pull request merged**
