### PR TITLE
Started the transformation to use the auth from firebase_auth_rest.

### PR DESCRIPTION
**Pull request by guyluz11**
Need more changes but this is start.

#66

### CODE REVIEW

**Comment by guyluz11** [comment]
Tests faile

I have tested only changing data and listening to changes (on native dart), other functionality might work too. 
In #65 the streams stop working after couple of hours, here (for now) there is error thrown out instead 

Error

**Comment by guyluz11** [comment]
Add fix for issue  #51.
All tests are now passing.

@cachapa can you go through the pull request and tell me what you think?.

**Comment by cachapa** [comment]
Hey sorry for the delay, things have been quite hectic lately.
I'll try to find some time to look at this over the weekend and report back.

**Comment by guyluz11** [comment]
Great,
I decided to move to other technology so I am not in a harry with this pull request.
Never the less I will try to fix any errors and changes that will come up just for the sake of helping this package.

**Comment by prateekmedia** [comment]
@cachapa Can you merge this PR, this literally brings the syntax of default firebase packages to firedart.

**Comment by cachapa** [comment]
Sorry but this is a huge PR that changes too many things for me to be comfortable just blindly merging it.
It also looks like it's a breaking change from the current API which I'm uncomfortable doing without a lot of thought.

I'm not sure copying the default Firebase package syntax is such a worthy goal anyway. I remember the last time I used it explicitly disliking a lot of their design choices - TBF this was many years ago so I have no idea if/how it's changed meanwhile.

In any case the reality is that I currently don't have the free time to maintain this package, so until that changes I would encourage you to use a fork.

**Comment by guyluz11** [comment]
> Sorry but this is a huge PR that changes too many things for me to be comfortable just blindly merging it. It also looks like it's a breaking change from the current API which I'm uncomfortable doing without a lot of thought.
> 
> I'm not sure copying the default Firebase package syntax is such a worthy goal anyway. I remember the last time I used it explicitly disliking a lot of their design choices - TBF this was many years ago so I have no idea if/how it's changed meanwhile.
> 
> In any case the reality is that I currently don't have the free time to maintain this package, so until that changes I would encourage you to use a fork.

Can you stat what API does it breaks?.

Suggestion in general, you can use the checkbox at the top column of each file to signal what files you went through and they are okay.
It's good process both to yourself and for others

**Comment by cachapa** [comment]
> Can you stat what API does it breaks?.

Changing the `initialize` method signature, moving auth and user methods to the Firedart class, are the ones I noticed immediately.
There are reasons why auth was made a separate and optional component.

> Suggestion in general, you can use the checkbox at the top column of each file to signal what files you went through and they are okay.
> It's good process both to yourself and for others

I'm aware of how PR reviews work, thanks.

It's not about looking at the code, but the time it takes to test it to make sure it does what's expected without introducing errors or unwanted behavioural changes. That takes time and becomes exponentialy harder with the amount of code being reviewed.

In general it's bad form to perform large changes or to refactor code without discussing it beforehand since you put the maintainer in a difficult position: I'm not comfortable throwing away your effort but also do not appreciate having my API design changed without consultation.

It also pressures me to spend my free time reviewing this code which I currently do not really have. Remember that with very few exceptions, open source contributors aren't paid for their work.

**Comment by prateekmedia** [comment]
@cachapa Do you feel that this project needs a maintainer? I think @guyluz11 might volunteer for that.

**Comment by guyluz11** [comment]
> @cachapa Do you feel that this project needs a maintainer? I think @guyluz11 might volunteer for that.

I prefer not. I stopped using this package.

**Pull request closed without merging**
