### PR TITLE
Change API to look more like cloud_firestore, collection queries

### PR DESCRIPTION
**Pull request by illia-romanenko**
- basic collection queries support
- change API to look more like cloud_firestore
- reformat files/classes
- add linter
- auth gateway URL configuration

### CODE REVIEW

**Comment by bootstraponline** [comment]
> #### Conflicting files
> `analysis_options.yaml`
> `lib/firestore/firestore_gateway.dart`
> `lib/firestore/models.dart`

Looks like there's a merge conflict.

**Comment by SwissCheese5** [comment]
This pull request is a bit too large and changes too much. It might be best to split it across several PRs. For example, I'm sure @cachapa would agree to the colleciton query support and that is the feature I need the most.

Perhaps renaming could be a PR, queries could be a PR, the linter a PR, etc...

**Comment by illia-romanenko** [comment]
Yeah - those are great ideas! And I saw @SwissCheese5 PR that did just that - that's awesome! 

At the time we don't have much time to split it nicely due to the large amount of changes/work we have. I hope that somebody could try to split it like @SwissCheese5 and prepare more granular PRs.

**Comment by cachapa** [comment]
Hey thanks for the effort. Given that @SwissCheese5 has distilled the query support in PR #23 I'm going to close this one.

As for the other changes, we can discuss how much sense they make. Changing the API can be worthwhile but I think it requires a bigger discussion (and it would certainly involve a major version change).

**Pull request closed without merging**
